[package]
name = "lact-schema"
version = "0.4.5"
edition = "2021"

[features]
args = ["clap"]

[dependencies]
amdgpu-sysfs = { version = "0.12.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
indexmap = { version = "*", features = ["serde"] }
clap = { version = "4.4.2", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"
