[package]
name = "lact-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
amdgpu-sysfs = { git = "https://github.com/ilya-zlobintsev/amdgpu-sysfs-rs", branch = "error", features = [
    "serde",
] }
serde = { version = "1.0", features = ["derive"] }
indexmap = { version = "1.9", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
