[package]
name = "lact-schema"
version = "0.3.2"
edition = "2021"

[dependencies]
amdgpu-sysfs = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
indexmap = { version = "*", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
