[package]
name = "lact-gui"
version = "0.2.0"
authors = ["Ilya Zlobintsev <ilya.zl@protonmail.com>"]
edition = "2021"

[dependencies]
lact-client = { path = "../lact-client" }
lact-daemon = { path = "../lact-daemon" }
gtk = { version = "0.6", package = "gtk4" }
once_cell = "1.17.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
