[package]
name = "lact-gui"
version = "0.2.0"
authors = ["Ilya Zlobintsev <ilya.zl@protonmail.com>"]
edition = "2021"

[dependencies]
lact-client = { path = "../lact-client" }
gtk = "0.16"
# pango = "0.16"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix = "0.26"
anyhow = "1.0"
serde_json = "1.0"
serde = "1.0"
