[package]
name = "lact"
version = "0.1.0"
edition = "2021"

[features]
default = ["lact-gui"]

[dependencies]
lact-daemon = { path = "../lact-daemon" }
lact-gui = { path = "../lact-gui", optional = true }
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
