[package]
name = "lact-daemon"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amdgpu-sysfs = { path = "../../amdgpu-sysfs-rs", features = ["serde"] }
anyhow = "1.0"
bincode = "1.3"
nix = "0.25"
pciid-parser = { version = "0.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.21.2", features = [
    "rt",
    "macros",
    "net",
    "io-util",
    "time",
    "signal",
    "sync",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
lact-schema = { path = "../lact-schema" }
indexmap = { version = "1.9", features = ["serde"] }
