[package]
name = "lact-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amdgpu-sysfs = { git = "https://github.com/ilya-zlobintsev/amdgpu-sysfs-rs", branch = "blocking", features = [
    "serde",
] }
anyhow = "1.0.66"
bincode = "1.3.3"
nix = "0.25.0"
pciid-parser = { version = "0.6.2", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.14"
tokio = { version = "1.21.2", features = [
    "rt",
    "macros",
    "net",
    "io-util",
    "time",
    "signal",
    "sync",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
vulkano = "0.32.1"
lact-schema = { path = "../lact-schema" }
