[package]
name = "lact-client"
version = "0.5.2"
edition = "2021"

[dependencies]
lact-schema = { path = "../lact-schema" }
anyhow = "1.0.79"
nix = { version = "0.27.1", default-features = false }
serde = "1.0.195"
tracing = "0.1.40"
serde_json = "1.0.111"
