[package]
name = "lact-client"
version = "0.4.5"
edition = "2021"

[dependencies]
lact-schema = { path = "../lact-schema" }
anyhow = "1.0.75"
nix = { version = "0.27.1", default-features = false }
serde = "1.0.188"
tracing = "0.1.37"
serde_json = "1.0.106"
