[package]
name = "lact-client"
version = "0.1.0"
edition = "2021"

[dependencies]
lact-schema = { path = "../lact-schema" }
anyhow = "1.0.68"
nix = { version = "0.26.2", default-features = false }
serde = "1.0.152"
tracing = "0.1.37"
serde_json = "1.0.91"
