name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Update repos
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install libgtk-3-dev libvulkan-dev
    - name: Update pci.ids
      run: sudo sh -c "curl https://pci-ids.ucw.cz/v2.2/pci.ids > /usr/share/misc/pci.ids"
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
